### ISSUE TITLE
Failed to install GitLab 7.2 on Debian 7 x64

### ISSUE THREAD

**Issue by lexrus** [debops/ansible-gitlab#1]
![screen shot 2014-09-12 at 9 31 00 pm](https://cloud.githubusercontent.com/assets/219689/4250220/32671438-3a81-11e4-88b7-0156ed73a687.png)

**Comment by drybjed** [comment]
@lexrus New GitLab role has some improvements you might be interested.

It's now easier to backport Ruby 2.1 in Debian - you needto set `ruby_version: 'backport'` and packages from Jessie should be correctly built and installed. You can also use external repositories with Ruby 2.1 if you so choose.

`debops.gitlab` has now a list with groups `git` user should be added into. If you use the role separately, you can just set this list as empty `[]` and Ansible shouldn't bother you anymore about missing groups.

Let me know if there are any other issues with using the role. :-)

**Comment by lexrus** [comment]
@drybjed :+1:
But recently I'd prefer the new OmniBus package from GitLab. I've created my oneclick playbook for it: https://github.com/lexrus/ios-dev-playbook

Anyway, thank you.
