### ISSUE TITLE
Gitlab fails on initializing DB

### ISSUE THREAD

**Issue by devnoop** [debops/ansible-gitlab#61]
Hello,

try to install gitlab on a debian-based system. 
The first run of debops throws the following error. The second run throws no error, but gitlab isnt reacable.  

debops inventory: 

``
[debops_all_hosts]
testing

[debops_service_gitlab]
testing
``

taget-system:  vagrant box with "debian/jessie64"

error message:

``
TASK [debops.gitlab : Initialize GitLab database] ******************************
fatal: [testing]: FAILED! => {"changed": true, "cmd": "yes 'yes' | bundle exec rake gitlab:setup RAILS_ENV=production", "delta": "0:00:06.357969", "end": "2016-10-29 23:24:29.973947", "failed": true, "rc": 1, "start": "2016-10-29 23:24:23.615978", "stderr": "Missing Rails.application.secrets.secret_key_base for production environment. The secret will be generated and stored in config/secrets.yml.\nMissing Rails.application.secrets.otp_key_base for production environment. The secret will be generated and stored in config/secrets.yml.\nMissing Rails.application.secrets.db_key_base for production environment. The secret will be generated and stored in config/secrets.yml.\nCan't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/mysql2-0.3.20/lib/mysql2/client.rb:70:in `connect'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/mysql2-0.3.20/lib/mysql2/client.rb:70:in `initialize'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `new'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `mysql2_connection'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'\n/usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'\n/usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_handling.rb:113:in `retrieve_connection'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_handling.rb:87:in `connection'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/tasks/mysql_database_tasks.rb:8:in `connection'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/tasks/mysql_database_tasks.rb:42:in `drop'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:114:in `drop'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:128:in `block in drop_current'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:276:in `block in each_current_configuration'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:275:in `each'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:275:in `each_current_configuration'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:127:in `drop_current'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/railties/databases.rake:28:in `block (2 levels) in <top (required)>'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `call'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'\n/usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/railties/databases.rake:141:in `block (2 levels) in <top (required)>'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `call'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'\n/usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'\n/var/local/git/gitlab/lib/tasks/gitlab/setup.rake:17:in `setup_db'\n/var/local/git/gitlab/lib/tasks/gitlab/setup.rake:4:in `block (2 levels) in <top (required)>'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `call'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'\n/usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `each'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/bin/rake:23:in `load'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/bin/rake:23:in `<main>'\nCouldn't drop gitlabhq_production\n#<Mysql2::Error: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)>\nCouldn't create database for {\"adapter\"=>\"mysql2\", \"encoding\"=>\"utf8\", \"reconnect\"=>false, \"database\"=>\"gitlabhq_production\", \"pool\"=>10, \"username\"=>\"gitlab\", \"password\"=>\"AdHjIOmKryq-gEp_lAQEeIww:8LKn3T4WKzkezvPSRh3W3mf\", \"host\"=>nil}, {:charset=>\"utf8\", :collation=>\"utf8_unicode_ci\"}\n(If you set the charset manually, make sure you have a matching collation)\nrake aborted!\nMysql2::Error: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/mysql2-0.3.20/lib/mysql2/client.rb:70:in `connect'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/mysql2-0.3.20/lib/mysql2/client.rb:70:in `initialize'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `new'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `mysql2_connection'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_handling.rb:113:in `retrieve_connection'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_handling.rb:87:in `connection'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:648:in `connection'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:664:in `block in method_missing'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:634:in `block in say_with_time'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:634:in `say_with_time'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:654:in `method_missing'\n/var/local/git/gitlab/db/schema.rb:17:in `block in <top (required)>'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/schema.rb:41:in `instance_eval'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/schema.rb:41:in `define'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/schema.rb:61:in `define'\n/var/local/git/gitlab/db/schema.rb:14:in `<top (required)>'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:219:in `load_schema_for'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:236:in `block in load_schema_current'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:276:in `block in each_current_configuration'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:275:in `each'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:275:in `each_current_configuration'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:235:in `load_schema_current'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/railties/databases.rake:247:in `block (3 levels) in <top (required)>'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/railties/databases.rake:251:in `block (3 levels) in <top (required)>'\n/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/railties/databases.rake:142:in `block (2 levels) in <top (required)>'\n/var/local/git/gitlab/lib/tasks/gitlab/setup.rake:17:in `setup_db'\n/var/local/git/gitlab/lib/tasks/gitlab/setup.rake:4:in `block (2 levels) in <top (required)>'\nTasks: TOP => db:schema:load\n(See full trace by running task with --trace)\nyes: standard output: Broken pipe\nyes: write error", "stdout": "This will create the necessary database tables and seed the database.\nYou will lose any previous data stored in the database.\nDo you want to continue (yes/no)? \n-- enable_extension(\"plpgsql\")", "stdout_lines": ["This will create the necessary database tables and seed the database.", "You will lose any previous data stored in the database.", "Do you want to continue (yes/no)? ", "-- enable_extension(\"plpgsql\")"], "warnings": []}
``

**Comment by drybjed** [comment]
GitLab requres a database, but the role does not manage the server side, only the client side. The default database used in the role is MariaDB/MySQL. Try adding to inventory:
```
[debops_service_mariadb_server]
testing
```
This should ensure that the MariaDB server is installed and configured before the GitLab role, and ready to process connections.

**Comment by devnoop** [comment]
Thank you!

I used a new VM and added this inventory: 

```
[debops_all_hosts]
testing

[debops_service_mariadb_server]
testing

[debops_service_gitlab]
testing
```

but now I get another error: 

```
TASK [debops.mariadb : Create databases] ***************************************
failed: [testing] (item={u'database': u'gitlabhq_production'}) => {"item": {"database": "gitlabhq_production"}, "msg": "Failed to connect to the host via ssh.", "unreachable": true}
fatal: [testing]: UNREACHABLE! => {"changed": false, "msg": "All items completed", "results": [{"_ansible_item_result": true, "item": {"database": "gitlabhq_production"}, "msg": "Failed to connect to the host via ssh.", "unreachable": true}]}
```

does it come from the target or from my local ansible instance?

**Comment by drybjed** [comment]
Let me guess, you are running Ansible on the same host that it manages, since it's Vagrant. In that case Ansible Controller and remote host are the same.

The `debops.mariadb` and `debops.mariadb_server` roles are written in a way to prevent Ansible Controller messing with the wrong database - this works fine when the remote host is different than Ansible Controller, but when they are the same, you need to force the roles to cooperate.

Add this to the `inventory/host_vars/testing/mariadb.yml` file:
```yaml
---

# Ensure that Ansible delegates the tasks correctly to the same host
mariadb_server__delegate_to: 'localhost'
mariadb__delegate_to: 'localhost'
```
This should help move things along.

**Comment by devnoop** [comment]
No, there are different hosts. I execute debops on my localhost and connect to my remote host by 

`testing ansible_ssh_host=192.168.50.10 ansible_ssh_private_key_file=/home/xxx/repos/debops-xxx-services/.vagrant/machines/testing/virtualbox/private_key ansible_ssh_user=vagrant`

**Comment by devnoop** [comment]
there was a problem with my dns. 

setting: 

```
mariadb__delegate_to: 'my-taget-ip'
mariadb_server__delegate_to: 'my-target-ip'
```
in my hostvars solves the problem in my env. 
thx @drybjed
