### ISSUE TITLE
RFC: Drop MySQL/MariaDB support

### ISSUE THREAD

**Issue by bfabio** [debops/ansible-gitlab#82]
Rationale:
The role is quite complex by itself, the reasons being:
- The fast pace upstream develops GitLab (this would be enough work already).
- Support for different GitLab versions
- Support for different distros
- Support for both MySQL/MariaDB and PostgreSQL.

Supporting all those possible premutations makes the complexity explode really fast.

My proposal is to drop at least MySQL/MariaDB, as per 
https://docs.gitlab.com/ce/install/requirements.html#database, where they _strongly_ hint not to use MySQL and mention some features are even missing when you do.

Also, there are other pain points not mentioned I experienced myself with character encodings which we just don't handle. There is a [whole document](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/install/database_mysql.md) describing how to unfuck that mess.

**Comment by drybjed** [comment]
Sounds good to me. Current `master` branch does not have that many changes, so the drop could be done right now instead of waiting for the next release. Do you want to work on PR for this?

**Comment by bfabio** [comment]
Sure, I'll give it a try ASAP.

**Comment by bfabio** [comment]
Fixed in https://github.com/debops/debops-playbooks/pull/386.
